// Generated by grokhack.com /forge from Blockchains/grokhack-index. Edit freely.
export const FORGE = {
  "title": "Grok Tools Chat",
  "idea": "A chat assistant that can look up GitHub repos and do maths with tools",
  "repoUrl": "https://github.com/Blockchains/grok-tools-chat",
  "defaultModel": "grok-4.7",
  "indexModels": [
    "grok-4.6",
    "grok-4.5",
    "grok-4.3",
    "grok-4.20",
    "grok-4.1",
    "grok-4",
    "grok-4.20-non-reasoning",
    "grok-4-fast",
    "grok-4-fast-non-reasoning",
    "grok-4-fast-reasoning"
  ],
  "features": {
    "tool_calling": true,
    "live_search": false,
    "structured_output": false,
    "streaming": true,
    "vision": false,
    "scheduled": false
  },
  "systemPrompt": "You are the engine of 'Grok Tools Chat'. App idea: A chat assistant that can look up GitHub repos and do maths with tools. Be accurate, cite sources when you use search, and say clearly when you do not know."
} as const satisfies {
  title: string; idea: string; repoUrl: string; defaultModel: string; indexModels: readonly string[]
  features: Record<string, boolean>; systemPrompt: string
}
